ports:
  - port: 3000
    onOpen: open-browser
  - port: 5000
    onOpen: ignore

tasks:
- command: git status
- command: |
    pip3 install -r requirements.txt &&
    FLASK_DEBUG=1 FLASK_APP=backend/metrics-api.py python3 -m flask run --host=0.0.0.0
- command: |
    (cd frontend && npm install) &&
    CHOKIDAR_USEPOLLING=true NODE_ENV=development REACT_APP_METRICS_BASE_URL=`gp url 5000` npm start
