name: S3 Deploy

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: frontend

jobs:
  run:
    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: Configure AWS Credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: us-west-2
#    - name: Build static site
#      working-directory: frontend
#      run: npm ci && npm run build
#    - name: Deploy static site to S3 bucket
#      working-directory: frontend
#      run: aws s3 sync ./build/ s3://${{ secrets.S3_BUCKET }} --delete
  
      
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v1
      - name: Build static site
        working-directory: frontend
        run: npm ci && npm run build
      - name: Deploy
        uses: reggionick/s3-deploy@v1
        with:
          folder: frontend/build
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
